/* eslint @typescript-eslint/camelcase: 0 */
export const config = {
    images: {
        base_url: "http://image.tmdb.org/t/p/",
        secure_base_url: "https://image.tmdb.org/t/p/",
        backdrop_sizes: ["w300", "w780", "w1280", "original"],
        logo_sizes: ["w45", "w92", "w154", "w185", "w300", "w500", "original"],
        poster_sizes: ["w92", "w154", "w185", "w342", "w500", "w780", "original"],
        profile_sizes: ["w45", "w185", "h632", "original"],
        still_sizes: ["w92", "w185", "w300", "original"],
    },
    change_keys: [
        "adult",
        "air_date",
        "also_known_as",
        "alternative_titles",
        "biography",
        "birthday",
        "budget",
        "cast",
        "certifications",
        "character_names",
        "created_by",
        "crew",
        "deathday",
        "episode",
        "episode_number",
        "episode_run_time",
        "freebase_id",
        "freebase_mid",
        "general",
        "genres",
        "guest_stars",
        "homepage",
        "images",
        "imdb_id",
        "languages",
        "name",
        "network",
        "origin_country",
        "original_name",
        "original_title",
        "overview",
        "parts",
        "place_of_birth",
        "plot_keywords",
        "production_code",
        "production_companies",
        "production_countries",
        "releases",
        "revenue",
        "runtime",
        "season",
        "season_number",
        "season_regular",
        "spoken_languages",
        "status",
        "tagline",
        "title",
        "translations",
        "tvdb_id",
        "tvrage_id",
        "type",
        "video",
        "videos",
    ],
};

export const movies = {
    page: 1,
    total_results: 10000,
    total_pages: 500,
    results: [
        {
            popularity: 113.623,
            vote_count: 1805,
            video: false,
            poster_path: "/4gpW4MkRI0BB17GHOJzXq0WamDP.jpg",
            id: 300671,
            adult: false,
            backdrop_path: "/hY8myWhjSOUeeiPskhOfwwgaCwc.jpg",
            original_language: "en",
            original_title: "13 Hours: The Secret Soldiers of Benghazi",
            genre_ids: [28, 36, 53],
            title: "13 Hours: The Secret Soldiers of Benghazi",
            vote_average: 7.1,
            overview:
                "An American Ambassador is killed during an attack at a U.S. compound in Libya as a security team struggles to make sense out of the chaos.",
            release_date: "2016-01-13",
        },
        {
            popularity: 56.849,
            vote_count: 15540,
            video: false,
            poster_path: "/kSBXou5Ac7vEqKd97wotJumyJvU.jpg",
            id: 271110,
            adult: false,
            backdrop_path: "/m5O3SZvQ6EgD5XXXLPIP1wLppeW.jpg",
            original_language: "en",
            original_title: "Captain America: Civil War",
            genre_ids: [28, 12, 878],
            title: "Captain America: Civil War",
            vote_average: 7.4,
            overview:
                "Following the events of Age of Ultron, the collective governments of the world pass an act designed to regulate all superhuman activity. This polarizes opinion amongst the Avengers, causing two factions to side with Iron Man or Captain America, which causes an epic battle between former allies.",
            release_date: "2016-04-27",
        },
        {
            popularity: 29.953,
            id: 293660,
            video: false,
            vote_count: 21966,
            vote_average: 7.6,
            title: "Deadpool",
            release_date: "2016-02-09",
            original_language: "en",
            original_title: "Deadpool",
            genre_ids: [28, 12, 35],
            backdrop_path: "/n1y094tVDFATSzkTnFxoGZ1qNsG.jpg",
            adult: false,
            overview:
                "Deadpool tells the origin story of former Special Forces operative turned mercenary Wade Wilson, who after being subjected to a rogue experiment that leaves him with accelerated healing powers, adopts the alter ego Deadpool. Armed with his new abilities and a dark, twisted sense of humor, Deadpool hunts down the man who nearly destroyed his life.",
            poster_path: "/inVq3FRqcYIRl2la8iZikYYxFNR.jpg",
        },
    ],
};
